name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal_version: 1.5.1
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
      - run: shards install
      - run: crystal tool format src --check
      - name: crystal spec
        run: |
          sudo ln -s $(which wasm-ld-14 || which wasm-ld-13 || which wasm-ld-12 || which wasm-ld-11 || which wasm-ld-10) /usr/bin/wasm-ld
          ./spec.sh
